apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: whodistrod-cert
spec:
  secretName: whodistrod-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  commonName: "host.name"
  dnsNames:
    - "host.name"
