# syntax = docker/dockerfile:1

ARG NODE_VERSION=22.17.1
FROM node:${NODE_VERSION}-alpine AS base

WORKDIR /app

FROM base AS build

# Build environment variables
ARG VITE_ENV
ENV VITE_ENV=$VITE_ENV

RUN apk update && \
    apk add build-base gyp pkgconfig python3

COPY web/package-lock.json web/package.json ./
RUN npm ci

COPY web .

RUN npm run build


FROM nginx:stable-alpine-otel

# Build environment variables
ARG VITE_ENV
ENV VITE_ENV=$VITE_ENV

COPY --from=build /app/build /usr/share/nginx/html

COPY /infra/nginx.conf /etc/nginx/nginx.conf
# COPY /infra/upstreams.${VITE_ENV}.conf /etc/nginx/conf.d/upstreams.conf

EXPOSE 8080
CMD [ "/usr/sbin/nginx", "-g", "daemon off;" ]
