apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ns.yaml
  - cm.yaml
  - secrets.yaml
namespace: whodistrod-prod
images:
  - name: whodistrod-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:name"}
    newTag: web # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:tag"}
    digest: sha256:6d865f34022a844bbb4f3b3731b6a29cff6e8f88d37a6f55313bf0d3c3a94436 # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:digest"}
  - name: whodistrod-api-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:name"}
    newTag: api # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:tag"}
    digest: sha256:e42a269bcf9ebbecc8daa92e93264b5693dab8df078a8b32deacbdf9c22ec916 # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:digest"}
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: whodistrod-ingress
    path: ingress-patches.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: whodistrod-cert
    path: cert-patches.yaml
