apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ns.yaml
  - cm.yaml
  - secrets.yaml
namespace: whodistrod-prod
images:
  - name: whodistrod-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:name"}
    newTag: web # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:tag"}
    digest: sha256:7f475067fccbd5f0ebf0cb6a8e6c75d35cf23ff80872518993eb4a3f03abd3e3 # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:digest"}
  - name: whodistrod-api-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:name"}
    newTag: api # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:tag"}
    digest: sha256:068cb43c448f8698a51bc69c9915267e764d7fba3028d23dc9c902e51a5ac1be # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:digest"}
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: whodistrod-ingress
    path: ingress-patches.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: whodistrod-cert
    path: cert-patches.yaml
