apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ns.yaml
  - cm.yaml
  - secrets.yaml
namespace: whodistrod-prod
images:
  - name: whodistrod-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:name"}
    newTag: web # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:tag"}
    digest: sha256:c5de98d47effc3db1ac72bfb84edd98c562b13a99faaedb8051aa4c128b9ec9e # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:digest"}
  - name: whodistrod-api-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:name"}
    newTag: api # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:tag"}
    digest: sha256:195aaa726d6b6e76f1e50d7b56e18fb38e9253c9ae79be6e68ce9664c81b88bd # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:digest"}
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: whodistrod-ingress
    path: ingress-patches.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: whodistrod-cert
    path: cert-patches.yaml
