apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ns.yaml
  - cm.yaml
namespace: whodistrod-prod
images:
  - name: whodistrod-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:name"}
    newTag: web # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:tag"}
    digest: sha256:4f989951e0add0b5981472a40d9432997199df389cdd1e5ba4c42134823fa72f # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:digest"}
  - name: whodistrod-api-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:name"}
    newTag: api # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:tag"}
    digest: sha256:ca909c001382eb241e1c8395d97ce87b50922ec8809228c4cdf21ccde17d6e34 # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:digest"}
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: whodistrod-ingress
    path: ingress-patches.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: whodistrod-cert
    path: cert-patches.yaml
