apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ns.yaml
  - cm.yaml
  - secrets.yaml
namespace: whodistrod-prod
images:
  - name: whodistrod-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:name"}
    newTag: web # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:tag"}
    digest: sha256:bb018d65f39790034b9ef91d97e2c89868827ef993c03c9bad6ee89168e116f0 # {"$imagepolicy": "flux-system:whodistrod-image-policy-web-prod:digest"}
  - name: whodistrod-api-image
    newName: ghcr.io/and-fm/whodistrod # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:name"}
    newTag: api # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:tag"}
    digest: sha256:4097a6ff3adc5c60b6696c4a2bef8d2a05656fbabfa9e4058079266962aaf42f # {"$imagepolicy": "flux-system:whodistrod-image-policy-api-prod:digest"}
patches:
  - target:
      group: traefik.io
      version: v1alpha1
      kind: IngressRoute
      name: whodistrod-ingress
    path: ingress-patches.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: whodistrod-cert
    path: cert-patches.yaml
